api/urls.py
from rest_framework import routers
from .views import ProductViewSet

router = routers.DefaultRouter()
router.register(r'products', ProductViewSet)

base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from application.views import UserLogin
from base import settings
from api.urls import router

urlpatterns = [
    path("application/", include("application.urls")),
    path("admin/", admin.site.urls),
    path("", UserLogin.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page="login"), name="logout"),
    path("api/v1/", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("", include("social_django.urls")),
]
if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

learn_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from monolith.views import UserLogin
from learn_site import settings
from api.urls import router
urlpatterns = [
    path("monolith/", include("monolith.urls")),
    path("admin/", admin.site.urls),
    path('', UserLogin.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('api/v1/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

monolith/urls.py
from django.urls import path, include
from .views import (
    ProductList,
    BucketAddView,
    BucketView,
    DeleteBucketProductFirst,
    DeleteBucketProductAll,
    OrderCreateViewNew,
    OrderListView
)
app_name = 'monolith'
urlpatterns = [
    path('product/', include([
        path('list/', ProductList.as_view(), name='product_list'),
    ])),
    path('bucket/', include([
        path('create/', BucketAddView.as_view(), name='bucket_add'),
        path('prodcut_list/', BucketView.as_view(), name='bucket_detail'),
        path('delete_product/<int:pk>', DeleteBucketProductFirst.as_view(), name='delete_product_first'),
        path('delete_product_all/<int:pk>', DeleteBucketProductAll.as_view(), name='delete_product_all'),
    ])),

    path('order/', include([
        path('create/', OrderCreateViewNew.as_view(), name='order_create'),
        path('list/', OrderListView.as_view(), name='order_list'),
    ]))
]

application/models.py
from django.db import models
from .managers import BucketManager

from django.contrib.auth.models import AbstractUser

# Create your models here.

DB_SCHEMA = "store"


class User(AbstractUser):
    sale = models.IntegerField(null=True)


class TypeProduct(models.Model):
    name = models.CharField(null=False, verbose_name="Наименование", max_length=100)

    class Meta:
        db_table = f'{DB_SCHEMA}"."product_types'
        verbose_name = "Вид товара"
        verbose_name_plural = "Виды товара"

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(null=False, verbose_name="Название", max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        db_table = f'{DB_SCHEMA}"."brands'
        verbose_name = "Бренд"
        verbose_name_plural = "Бренды"


class Product(models.Model):
    name = models.CharField(max_length=100, null=False, verbose_name="Название")
    price = models.IntegerField(null=False, verbose_name="Цена")
    product_type = models.ForeignKey(
        TypeProduct, on_delete=models.RESTRICT, verbose_name="Вид продукта"
    )
    rating = models.IntegerField(null=False, verbose_name="Рейтинг продукта")
    guarantee = models.IntegerField(null=True, verbose_name="Гарантия (мес)")
    brand = models.ForeignKey(Brand, null=True, on_delete=models.CASCADE)

    class Meta:
        db_table = f'{DB_SCHEMA}"."products'
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

    def __str__(self):
        return self.name + f"({self.price})"


class Bucket(models.Model):
    user = models.ForeignKey(
        null=False,
        on_delete=models.CASCADE,
        verbose_name="Пользователь",
        to="User",
        default=1,
    )
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, verbose_name="Товар", null=False
    )
    status = models.BooleanField(
        verbose_name="Статус корзины", null=False, default=False
    )
    objects = BucketManager()

    class Meta:
        db_table = f'{DB_SCHEMA}"."buckets'
        verbose_name = "Корзина заказов"
        verbose_name_plural = "Корзины заказов"


class OrderStatus(models.Model):
    name = models.CharField(
        null=False, verbose_name="Название", max_length=100, default=1
    )

    class Meta:
        db_table = f'{DB_SCHEMA}"."order_statuses'
        verbose_name = "Статус заказа"
        verbose_name_plural = "Статусы заказа"


class Order(models.Model):
    status = models.ForeignKey(
        OrderStatus, on_delete=models.CASCADE, null=False, verbose_name="Статус заказа"
    )
    user = models.ForeignKey(
        to="User",
        on_delete=models.CASCADE,
        verbose_name="Пользователь",
        null=False,
        default=1,
    )
    order_date = models.DateTimeField(null=False, verbose_name="Дата заказа")
    issue_date = models.DateTimeField(null=True, verbose_name="Дата выдачи")
    total_price = models.IntegerField(
        null=False, default=0, verbose_name="Стоимость заказа"
    )

    class Meta:
        db_table = f'{DB_SCHEMA}"."orders'
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"


class ProductOrder(models.Model):
    order = models.ForeignKey(
        Order,
        verbose_name="Заказ",
        null=False,
        on_delete=models.CASCADE,
        related_name="products_order",
    )
    product = models.ForeignKey(
        Product, verbose_name="Продукт", null=False, on_delete=models.CASCADE
    )
    count = models.IntegerField(null=False, default=1, verbose_name="Количество товара")
    price = models.IntegerField(null=False, verbose_name="Цена")

    class Meta:
        db_table = f'{DB_SCHEMA}"."product_orders'
        verbose_name = "Товар и заказ"
        verbose_name_plural = "Товары и заказы"

monolith/templates/bucket/product_list.html
{% extends 'base.html' %}
{% block script %}
    <script>
        function delete_object(url)
        {
            let token = document.getElementsByName('csrfmiddlewaretoken')[0].value;
            fetch(url, {
                method:'POST',
                headers: { "X-CSRFToken": token },
            }).then(()=>window.location.href='');
        }
    </script>
{% endblock %}
{% block content %}
    <div class="container container-fluid">

     {% if bucket_list.count > 0 %}
         <form action="{% url 'monolith:order_create' %}" method="post">
         {% csrf_token %}
          <div class="card m-5">
                <div class="card-header">
                    <h5 class="mt-3">Товары к покупке</h5>
                </div>
                <div class="card-body">
                    <table class="table">
                    <thead>
                        <tr>
                            <th>Товар</th>
                            <th>Количество (шт)</th>
                            <th>Цена </th>
                            <th>Действия</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for bucket in bucket_list %}
                            <tr>
                                <td>
                                    <input type="hidden" name="product_id" value="{{bucket.product__id}}">
                                    {{bucket.product__name}}
                                </td>
                                <td>
                                    <input type="hidden" name="count_product" value="{{bucket.count_product}}">
                                    {{bucket.count_product}}
                                </td>
                                <td>
                                    <input type="hidden" name="price" value="{{bucket.sum_product}}">
                                    {{bucket.sum_product}} (руб)
                                </td>
                                <td>
                                    <span onclick="delete_object('{% url 'monolith:delete_product_all' bucket.product__id%}')"
                                    class="btn btn-outline-danger">
                                        Убрать из корзины
                                    </span>
                                    <span  class="btn btn-outline-dark"
                                           onclick="delete_object('{% url 'monolith:delete_product_first' bucket.product__id %}')">
                                             Уменьшить кол-во
                                    </span>
                                </td>
                            </tr>
                            {% endfor %}
                            <tr>
                                <th colspan="2">Итоговая цена</th>
                                <th colspan="2">
                                    <input type="hidden" name="total_price" value="{{total_price.sum_product__sum}}">
                                    {{total_price.sum_product__sum}} (руб)
                                </th>
                            </tr>
                    </tbody>
                </table>
                </div>
            <div class="card-footer text-end">
                <a href="#" class="btn btn-outline-danger">Отмена</a>
                <button type="submit" class="btn btn-outline-dark">
                        Перейти к оформлению
                </button>
            </div>
          </div>
        </form>
        {% else %}
            <div class="alert alert-info mt-4">
                <h5>Вы еще не выбрали товар !</h5>
            </div>
     {% endif %}
    </div>
{% endblock %}