api/urls.py
from rest_framework import routers
from .views import ProductViewSet

router = routers.DefaultRouter()
router.register(r'products', ProductViewSet)

application/urls.py
from django.urls import path, include
from .views import (
    ProductList,
    BucketAddView,
    BucketView,
    DeleteBucketProductFirst,
    DeleteBucketProductAll,
    OrderCreateView,
    OrderListView
)
app_name = 'application'
urlpatterns = [
    path('product/', include([
        path('list/', ProductList.as_view(), name='product_list'),
    ])),
    path('bucket/', include([
        path('create/', BucketAddView.as_view(), name='bucket_add'),
        path('prodcut_list/', BucketView.as_view(), name='bucket_detail'),
        path('delete_product/<int:pk>', DeleteBucketProductFirst.as_view(), name='delete_product_first'),
        path('delete_product_all/<int:pk>', DeleteBucketProductAll.as_view(), name='delete_product_all'),
    ])),
    path('order/', include([
        path('create/', OrderCreateView.as_view(), name='order_create'),
        path('list/', OrderListView.as_view(), name='order_list'),
    ]))
]

base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from application.views import UserLogin
from base import settings
from api.urls import router

urlpatterns = [
    path("application/", include("application.urls")),
    path("admin/", admin.site.urls),
    path("", UserLogin.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page="login"), name="logout"),
    path("api/v1/", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("", include("social_django.urls")),
]
if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

learn_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from monolith.views import UserLogin
from learn_site import settings
from api.urls import router
urlpatterns = [
    path("monolith/", include("monolith.urls")),
    path("admin/", admin.site.urls),
    path('', UserLogin.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('api/v1/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

application/models.py
from django.db import models
from .managers import BucketManager

from django.contrib.auth.models import AbstractUser

# Create your models here.

DB_SCHEMA = "store"


class User(AbstractUser):
    sale = models.IntegerField(null=True)


class TypeProduct(models.Model):
    name = models.CharField(null=False, verbose_name="Наименование", max_length=100)

    class Meta:
        db_table = f'{DB_SCHEMA}"."product_types'
        verbose_name = "Вид товара"
        verbose_name_plural = "Виды товара"

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(null=False, verbose_name="Название", max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        db_table = f'{DB_SCHEMA}"."brands'
        verbose_name = "Бренд"
        verbose_name_plural = "Бренды"


class Product(models.Model):
    name = models.CharField(max_length=100, null=False, verbose_name="Название")
    price = models.IntegerField(null=False, verbose_name="Цена")
    product_type = models.ForeignKey(
        TypeProduct, on_delete=models.RESTRICT, verbose_name="Вид продукта"
    )
    rating = models.IntegerField(null=False, verbose_name="Рейтинг продукта")
    guarantee = models.IntegerField(null=True, verbose_name="Гарантия (мес)")
    brand = models.ForeignKey(Brand, null=True, on_delete=models.CASCADE)

    class Meta:
        db_table = f'{DB_SCHEMA}"."products'
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

    def __str__(self):
        return self.name + f"({self.price})"


class Bucket(models.Model):
    user = models.ForeignKey(
        null=False,
        on_delete=models.CASCADE,
        verbose_name="Пользователь",
        to="User",
        default=1,
    )
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, verbose_name="Товар", null=False
    )
    status = models.BooleanField(
        verbose_name="Статус корзины", null=False, default=False
    )
    objects = BucketManager()

    class Meta:
        db_table = f'{DB_SCHEMA}"."buckets'
        verbose_name = "Корзина заказов"
        verbose_name_plural = "Корзины заказов"


class OrderStatus(models.Model):
    name = models.CharField(
        null=False, verbose_name="Название", max_length=100, default=1
    )

    class Meta:
        db_table = f'{DB_SCHEMA}"."order_statuses'
        verbose_name = "Статус заказа"
        verbose_name_plural = "Статусы заказа"


class Order(models.Model):
    status = models.ForeignKey(
        OrderStatus, on_delete=models.CASCADE, null=False, verbose_name="Статус заказа"
    )
    user = models.ForeignKey(
        to="User",
        on_delete=models.CASCADE,
        verbose_name="Пользователь",
        null=False,
        default=1,
    )
    order_date = models.DateTimeField(null=False, verbose_name="Дата заказа")
    issue_date = models.DateTimeField(null=True, verbose_name="Дата выдачи")
    total_price = models.IntegerField(
        null=False, default=0, verbose_name="Стоимость заказа"
    )

    class Meta:
        db_table = f'{DB_SCHEMA}"."orders'
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"


class ProductOrder(models.Model):
    order = models.ForeignKey(
        Order,
        verbose_name="Заказ",
        null=False,
        on_delete=models.CASCADE,
        related_name="products_order",
    )
    product = models.ForeignKey(
        Product, verbose_name="Продукт", null=False, on_delete=models.CASCADE
    )
    count = models.IntegerField(null=False, default=1, verbose_name="Количество товара")
    price = models.IntegerField(null=False, verbose_name="Цена")

    class Meta:
        db_table = f'{DB_SCHEMA}"."product_orders'
        verbose_name = "Товар и заказ"
        verbose_name_plural = "Товары и заказы"

application/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField()

application/views.py
import datetime

from django.http import HttpResponseRedirect
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic import TemplateView, DeleteView
from .models import *
from django_filters.views import FilterView
from .filters import ProductFilter
from services.bucket_service import BucketService


class ProductList(LoginRequiredMixin, FilterView):
    model = Product
    template_name = "product/list.html"
    queryset = Product.objects.all().select_related("product_type")
    filterset_class = ProductFilter
    paginate_by = 20

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductList, self).get_context_data()
        get_data = self.request.GET
        brand_id = get_data.get("brand_id", False)
        product_type_id = get_data.get("product_type_id", False)
        context_extra = {
            "brands": Brand.objects.all(),
            "product_types": TypeProduct.objects.all(),
            "brand_id": int(brand_id) if brand_id else "",
            "name": get_data.get("name", ""),
            "product_type_id": int(product_type_id) if product_type_id else "",
        }
        return context | context_extra


class BucketView(LoginRequiredMixin, TemplateView):
    template_name = "bucket/product_list.html"

    def get_context_data(self, **kwargs):
        context = super(BucketView, self).get_context_data()
        service = BucketService(user=self.request.user)
        object_list, pr_sum = service.get_products()
        context["object_list"] = object_list
        context["sum"] = pr_sum
        return context


class BucketAddView(LoginRequiredMixin, TemplateView):
    def post(self, request, *args, **kwargs):
        post = request.POST
        Bucket.objects.create(
            product_id=post.get("product"), client_id=request.user.client.id
        )
        return HttpResponseRedirect(redirect_to=reverse("application:bucket_detail"))


class UserLogin(LoginView):
    template_name = "login.html"
    next_page = reverse_lazy("application:product_list")
    redirect_authenticated_user = True


class DeleteBucketProductFirst(LoginRequiredMixin, DeleteView):
    model = Bucket

    def get_success_url(self):
        return reverse("application:bucket_detail")

    def get_queryset(self):
        return Bucket.objects.filter(product_id=self.kwargs.get("pk", False))

    def get_object(self, queryset=None):
        return self.get_queryset().first()


class DeleteBucketProductAll(DeleteBucketProductFirst):
    def delete(self, request, *args, **kwargs):
        deleted_products = self.queryset.all()
        for product in deleted_products:
            product.delete()
        return HttpResponseRedirect(self.success_url)


class OrderListView(LoginRequiredMixin, ListView):
    model = Order
    queryset = Order.objects.prefetch_related(
        "products_order", "products_order__product"
    )
    template_name = "orders.html"
    context_object_name = "orders"

    def get_queryset(self):
        return self.queryset.filter(client_id=self.request.user.client.id)


class OrderCreateView(LoginRequiredMixin, TemplateView):
    def post(self, request, *args, **kwargs):
        from .models import Order, ProductOrder, OrderStatus

        post = request.POST
        identity_list = post.getlist("product_id", [])
        count_list = post.getlist("count_product", [])
        price_list = post.getlist("price", [])
        total_price = post.get("total_price", 0)
        order = Order.objects.create(
            order_date=datetime.datetime.now(),
            status=OrderStatus.objects.get(name="Оформлен"),
            client_id=request.user.client.id,
            total_price=total_price,
        )
        created_list = []
        for index, pr_id in enumerate(identity_list):
            created_list.append(
                ProductOrder(
                    order_id=order.id,
                    product_id=pr_id,
                    count=count_list[index],
                    price=price_list[index],
                )
            )
        ProductOrder.objects.bulk_create(created_list)
        Bucket.objects.filter(product_id__in=identity_list).delete()
        return HttpResponseRedirect(reverse("application:order_list"))

application/templates/product/list.html
{% extends 'base.html' %}
{% block content %}
<div class="container container-fluid">
    <h5 class="mt-5">Товары</h5>
    <form method="get"  action="">
        <div class="accordion" id="product_filters">
            <div class="accordion-item">
                <h3 class="accordion-header" id="headingOne">
                     <button class="accordion-button" type="button"
                             data-bs-toggle="collapse" data-bs-target="#collapse_filters" aria-expanded="true" aria-controls="collapse_filters">
                        Фильтры
                     </button>
                </h3>
                <div id="collapse_filters" class="accordion-collapse collapse show"   data-bs-parent="#product_filters">
                    <div class="accordion-body">
                        <div class="input-group mt-3" style="width: 700px">
                            <span class="input-group-text">Бренд</span>
                            <select class="form-select" name="brand_id" style="width: 500px">
                                {% if brand_id %}
                                    <option value="">Ничего не выбрано</option>
                                {% else %}
                                    <option selected value="">Ничего не выбрано</option>
                                {% endif %}
                                {% for b in brands %}
                                    {% if b.id == brand_id %}
                                        <option selected value="{{b.pk}}">
                                           {{b.name}}
                                        </option>
                                    {% else %}
                                         <option  value="{{b.pk}}">
                                           {{b.name}}
                                        </option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </div>
                        <div class="input-group mt-3" style="width: 700px">
                            <span class="input-group-text">Название </span>
                            <input type="text" name="name" value="{{name}}" class="form-control">
                        </div>
                        <div class="input-group mt-3" style="width: 700px;">
                            <span class="input-group-text">Категория</span>
                            <select class="form-select" name="product_type_id">
                                {% if product_type_id %}
                                    <option value="">Ничего не выбрано</option>
                                    {% else %}
                                     <option  value="">Ничего не выбрано</option>
                                {% endif %}
                                {% for  pr_t in product_types %}
                                    {% if product_type_id == pr_t.pk %}
                                         <option selected value="{{pr_t.pk}}">
                                             {{pr_t.name}}
                                        </option>
                                    {% else %}
                                         <option value="{{pr_t.pk}}">
                                             {{pr_t.name}}
                                        </option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </div>
                        <div class="mt-3">
                            <a href="{% url 'application:product_list' %}" class="btn btn-outline-primary">
                                Сбросить
                            </a>
                            <button class="btn btn-outline-success">
                                 Применить
                            </button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
     </form>
    {% if product_list.count > 0 %}
         <table class="table mt-3 table-bordered">
        <thead>
         <tr>
             <th>Продукт</th>
             <th>Имя</th>
             <th>Цена</th>
             <th>Рейтинг</th>
             <th>Гарантия</th>
             <th>Действия</th>
         </tr>
        </thead>
        <tbody>
         {% for product in page_obj %}
              <tr>
                 <td>
                     {{product.product_type.name}}

                 </td>
                  <td>
                      {{ product.name }}
                  </td>
                  <td>
                      {{product.price}}
                  </td>
                  <td>
                      {{product.rating}}
                  </td>
                  <td>
                      {{product.guarantee}}
                  </td>
                  <td>
                      <div class="d-flex">
                          <a href="#" class="btn btn-outline-primary">Подробнее</a>
                          <form action="{% url 'application:bucket_add' %}" method="post" >
                          {% csrf_token %}
                          <input type="hidden" name="product" value="{{product.pk}}">
                          <input type="hidden" name="client" value="{{request.user.client.pk}}">
                           <button type="submit" class="btn btn-outline-success mx-2">
                             В корзину
                           </button>
                      </form>
                      </div>


                  </td>
              </tr>
         {% endfor %}
        </tbody>
    </table>
        <nav class="center-block">
        <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
        {% endif %}
          {% for i in page_obj.paginator.page_range %}
             <li class="page-item">
                 <a class="page-link" href="?page={{i}}">
                     {{i}}
                 </a>
             </li>
          {% endfor %}
          {% if page_obj.has_next %}
              <li class="page-item">
                  <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                      <span aria-hidden="true">&raquo;</span>
                  </a>
              </li>
          {%endif %}
        </ul>
    </nav>
        {% else %}
            <div class="alert  alert-primary mt-3">
                Ничего не найдено!
            </div>
    {% endif %}
</div>
{% endblock %}