api/urls.py
from rest_framework import routers
from .views import ProductViewSet

router = routers.DefaultRouter()
router.register(r'products', ProductViewSet)

base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from application.views import UserLogin
from base import settings
from api.urls import router

urlpatterns = [
    path("application/", include("application.urls")),
    path("admin/", admin.site.urls),
    path("", UserLogin.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page="login"), name="logout"),
    path("api/v1/", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("", include("social_django.urls")),
]
if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

learn_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from monolith.views import UserLogin
from learn_site import settings
from api.urls import router
urlpatterns = [
    path("monolith/", include("monolith.urls")),
    path("admin/", admin.site.urls),
    path('', UserLogin.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('api/v1/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

monolith/urls.py
from django.urls import path, include
from .views import (
    ProductList,
    BucketAddView,
    BucketView,
    DeleteBucketProductFirst,
    DeleteBucketProductAll,
    OrderCreateViewNew,
    OrderListView
)
app_name = 'monolith'
urlpatterns = [
    path('product/', include([
        path('list/', ProductList.as_view(), name='product_list'),
    ])),
    path('bucket/', include([
        path('create/', BucketAddView.as_view(), name='bucket_add'),
        path('prodcut_list/', BucketView.as_view(), name='bucket_detail'),
        path('delete_product/<int:pk>', DeleteBucketProductFirst.as_view(), name='delete_product_first'),
        path('delete_product_all/<int:pk>', DeleteBucketProductAll.as_view(), name='delete_product_all'),
    ])),

    path('order/', include([
        path('create/', OrderCreateViewNew.as_view(), name='order_create'),
        path('list/', OrderListView.as_view(), name='order_list'),
    ]))
]

monolith/templates/base.html
<!DOCTYPE html>
<html lang="en">

{% block script %}
{% endblock %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
         <a href="#" class="navbar-brand">Электорник</a>
        {% if request.user.is_authenticated %}
            <div class="collapse navbar-collapse ">
                <ul class="navbar-nav left">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'monolith:product_list' %}">
                            Товары
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'monolith:bucket_detail'%}" class="nav-link">
                            Корзина
                        </a>
                    </li>
                </ul>
            </div>
            <div class="collapse navbar-collapse flex-row-reverse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'monolith:order_list' %}">Заказы</a>
                    </li>
                    <li>
                        <a class="nav-link" href="#">Моя страница</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Выход</a>
                    </li>
                </ul>
            </div>
        {% endif %}
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>